server:
  host: 0.0.0.0
  port: "8001"
  mode: debug
  read_timeout: 60s
  write_timeout: 60s
  max_header_bytes: 1048576

database:
  host: localhost
  port: 3306
  user: root
  password: 123456
  name: instat
  charset: utf8mb4
  parseTime: true
  loc: Asia/Shanghai
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10

log:
  level: debug
  file: logs/server.log
  max_size: 100
  max_backups: 5
  max_age: 30
  compress: true

jwt:
  secret: "development-secret-key-change-in-production"
  expires: 24h
  refresh_ttl: 168h

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization
    - X-Requested-With
  allow_credentials: true

rate_limit:
  requests: 1000
  window: 1m
  enabled: true

grpc:
  port: 8002
  enabled: true

clickhouse:
  host: localhost
  port: 9000
  database: default
  username: default
  password: ""
  dial_timeout: 30s
  max_execution_time: 60s
  max_open_conns: 5
  max_idle_conns: 5
  conn_max_lifetime: 3600s
  block_buffer_size: 10
  max_compression_buffer: 10240
  client_info_product: gin-starter

debug: true
