server:
  host: 0.0.0.0
  port: 9000

log:
  level: debug
  file: logs/server.log

database:
  host: localhost
  port: 3306
  user: root
  password: ""
  name: gin_starter_dev
  charset: utf8mb4
  parseTime: "true"
  loc: "Asia/Shanghai"
