server:
  host: 0.0.0.0 # 监听地址，0.0.0.0 表示所有网卡都可访问
  port: 9500 # 监听端口，服务启动后会占用此端口

log:
  level: info # 日志级别，可选：debug、info、warn、error
  file: logs/server.log # 日志文件路径，日志将输出到此文件

cors:
  allowed_origins:
    - "https://example.com" # 允许跨域的来源（域名或地址）
    - "http://localhost:9500" # 本地开发环境允许的来源
  allowed_methods:
    - GET # 允许的 HTTP 方法
    - POST
    - PUT
    - DELETE
  allowed_headers:
    - Content-Type # 允许的请求头
    - Authorization
  allow_credentials: true # 是否允许携带认证信息（如 Cookie）

database:
  host: localhost # 数据库主机地址
  port: 3306 # 数据库端口
  user: root # 数据库用户名
  password: 123456 # 数据库密码
  name: "instat" # 数据库名称
  charset: "utf8mb4" # 数据库字符集
  parseTime: "true" # 是否解析时间
  loc: "Asia/Shanghai" # 时区

redis:
  host: localhost
  port:
