// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: install_event.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建安装事件请求
type CreateInstallEventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AppId            string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName          string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppVersion       string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	AppType          uint32                 `protobuf:"varint,4,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	EventId          string                 `protobuf:"bytes,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTime        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	DeviceId         string                 `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ChannelId        string                 `protobuf:"bytes,8,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	InstallIp        string                 `protobuf:"bytes,9,opt,name=install_ip,json=installIp,proto3" json:"install_ip,omitempty"`
	InstallType      uint32                 `protobuf:"varint,10,opt,name=install_type,json=installType,proto3" json:"install_type,omitempty"`
	InstallResult    uint32                 `protobuf:"varint,11,opt,name=install_result,json=installResult,proto3" json:"install_result,omitempty"`
	OsLanguage       string                 `protobuf:"bytes,12,opt,name=os_language,json=osLanguage,proto3" json:"os_language,omitempty"`
	OsTimezone       string                 `protobuf:"bytes,13,opt,name=os_timezone,json=osTimezone,proto3" json:"os_timezone,omitempty"`
	OsName           string                 `protobuf:"bytes,14,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OsVersion        string                 `protobuf:"bytes,15,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsBuild          string                 `protobuf:"bytes,16,opt,name=os_build,json=osBuild,proto3" json:"os_build,omitempty"`
	OsFamily         string                 `protobuf:"bytes,17,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	SignatureStatus  uint32                 `protobuf:"varint,18,opt,name=signature_status,json=signatureStatus,proto3" json:"signature_status,omitempty"`
	SignatureVersion string                 `protobuf:"bytes,19,opt,name=signature_version,json=signatureVersion,proto3" json:"signature_version,omitempty"`
	SignatureParams  map[string]string      `protobuf:"bytes,20,rep,name=signature_params,json=signatureParams,proto3" json:"signature_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateInstallEventRequest) Reset() {
	*x = CreateInstallEventRequest{}
	mi := &file_install_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstallEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstallEventRequest) ProtoMessage() {}

func (x *CreateInstallEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_install_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstallEventRequest.ProtoReflect.Descriptor instead.
func (*CreateInstallEventRequest) Descriptor() ([]byte, []int) {
	return file_install_event_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInstallEventRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateInstallEventRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateInstallEventRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *CreateInstallEventRequest) GetAppType() uint32 {
	if x != nil {
		return x.AppType
	}
	return 0
}

func (x *CreateInstallEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateInstallEventRequest) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *CreateInstallEventRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CreateInstallEventRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CreateInstallEventRequest) GetInstallIp() string {
	if x != nil {
		return x.InstallIp
	}
	return ""
}

func (x *CreateInstallEventRequest) GetInstallType() uint32 {
	if x != nil {
		return x.InstallType
	}
	return 0
}

func (x *CreateInstallEventRequest) GetInstallResult() uint32 {
	if x != nil {
		return x.InstallResult
	}
	return 0
}

func (x *CreateInstallEventRequest) GetOsLanguage() string {
	if x != nil {
		return x.OsLanguage
	}
	return ""
}

func (x *CreateInstallEventRequest) GetOsTimezone() string {
	if x != nil {
		return x.OsTimezone
	}
	return ""
}

func (x *CreateInstallEventRequest) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *CreateInstallEventRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *CreateInstallEventRequest) GetOsBuild() string {
	if x != nil {
		return x.OsBuild
	}
	return ""
}

func (x *CreateInstallEventRequest) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *CreateInstallEventRequest) GetSignatureStatus() uint32 {
	if x != nil {
		return x.SignatureStatus
	}
	return 0
}

func (x *CreateInstallEventRequest) GetSignatureVersion() string {
	if x != nil {
		return x.SignatureVersion
	}
	return ""
}

func (x *CreateInstallEventRequest) GetSignatureParams() map[string]string {
	if x != nil {
		return x.SignatureParams
	}
	return nil
}

// 创建安装事件响应
type CreateInstallEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstallEventResponse) Reset() {
	*x = CreateInstallEventResponse{}
	mi := &file_install_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstallEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstallEventResponse) ProtoMessage() {}

func (x *CreateInstallEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_install_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstallEventResponse.ProtoReflect.Descriptor instead.
func (*CreateInstallEventResponse) Descriptor() ([]byte, []int) {
	return file_install_event_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInstallEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateInstallEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 批量创建安装事件请求
type CreateInstallEventBatchRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Events        []*CreateInstallEventRequest `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstallEventBatchRequest) Reset() {
	*x = CreateInstallEventBatchRequest{}
	mi := &file_install_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstallEventBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstallEventBatchRequest) ProtoMessage() {}

func (x *CreateInstallEventBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_install_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstallEventBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateInstallEventBatchRequest) Descriptor() ([]byte, []int) {
	return file_install_event_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInstallEventBatchRequest) GetEvents() []*CreateInstallEventRequest {
	if x != nil {
		return x.Events
	}
	return nil
}

// 批量创建安装事件响应
type CreateInstallEventBatchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProcessedCount int32                  `protobuf:"varint,3,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateInstallEventBatchResponse) Reset() {
	*x = CreateInstallEventBatchResponse{}
	mi := &file_install_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstallEventBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstallEventBatchResponse) ProtoMessage() {}

func (x *CreateInstallEventBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_install_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstallEventBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateInstallEventBatchResponse) Descriptor() ([]byte, []int) {
	return file_install_event_proto_rawDescGZIP(), []int{3}
}

func (x *CreateInstallEventBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateInstallEventBatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateInstallEventBatchResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

var File_install_event_proto protoreflect.FileDescriptor

const file_install_event_proto_rawDesc = "" +
	"\n" +
	"\x13install_event.proto\x12\bprotobuf\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x06\n" +
	"\x19CreateInstallEventRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x12\x19\n" +
	"\bapp_type\x18\x04 \x01(\rR\aappType\x12\x19\n" +
	"\bevent_id\x18\x05 \x01(\tR\aeventId\x129\n" +
	"\n" +
	"event_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12\x1b\n" +
	"\tdevice_id\x18\a \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\b \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"install_ip\x18\t \x01(\tR\tinstallIp\x12!\n" +
	"\finstall_type\x18\n" +
	" \x01(\rR\vinstallType\x12%\n" +
	"\x0einstall_result\x18\v \x01(\rR\rinstallResult\x12\x1f\n" +
	"\vos_language\x18\f \x01(\tR\n" +
	"osLanguage\x12\x1f\n" +
	"\vos_timezone\x18\r \x01(\tR\n" +
	"osTimezone\x12\x17\n" +
	"\aos_name\x18\x0e \x01(\tR\x06osName\x12\x1d\n" +
	"\n" +
	"os_version\x18\x0f \x01(\tR\tosVersion\x12\x19\n" +
	"\bos_build\x18\x10 \x01(\tR\aosBuild\x12\x1b\n" +
	"\tos_family\x18\x11 \x01(\tR\bosFamily\x12)\n" +
	"\x10signature_status\x18\x12 \x01(\rR\x0fsignatureStatus\x12+\n" +
	"\x11signature_version\x18\x13 \x01(\tR\x10signatureVersion\x12c\n" +
	"\x10signature_params\x18\x14 \x03(\v28.protobuf.CreateInstallEventRequest.SignatureParamsEntryR\x0fsignatureParams\x1aB\n" +
	"\x14SignatureParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x1aCreateInstallEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x1eCreateInstallEventBatchRequest\x12;\n" +
	"\x06events\x18\x01 \x03(\v2#.protobuf.CreateInstallEventRequestR\x06events\"~\n" +
	"\x1fCreateInstallEventBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fprocessed_count\x18\x03 \x01(\x05R\x0eprocessedCount2\xe6\x01\n" +
	"\x13InstallEventService\x12_\n" +
	"\x12CreateInstallEvent\x12#.protobuf.CreateInstallEventRequest\x1a$.protobuf.CreateInstallEventResponse\x12n\n" +
	"\x17CreateInstallEventBatch\x12(.protobuf.CreateInstallEventBatchRequest\x1a).protobuf.CreateInstallEventBatchResponseB<Z:github.com/iswangwenbin/gin-starter/internal/grpc/protobufb\x06proto3"

var (
	file_install_event_proto_rawDescOnce sync.Once
	file_install_event_proto_rawDescData []byte
)

func file_install_event_proto_rawDescGZIP() []byte {
	file_install_event_proto_rawDescOnce.Do(func() {
		file_install_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_install_event_proto_rawDesc), len(file_install_event_proto_rawDesc)))
	})
	return file_install_event_proto_rawDescData
}

var file_install_event_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_install_event_proto_goTypes = []any{
	(*CreateInstallEventRequest)(nil),       // 0: protobuf.CreateInstallEventRequest
	(*CreateInstallEventResponse)(nil),      // 1: protobuf.CreateInstallEventResponse
	(*CreateInstallEventBatchRequest)(nil),  // 2: protobuf.CreateInstallEventBatchRequest
	(*CreateInstallEventBatchResponse)(nil), // 3: protobuf.CreateInstallEventBatchResponse
	nil,                                     // 4: protobuf.CreateInstallEventRequest.SignatureParamsEntry
	(*timestamppb.Timestamp)(nil),           // 5: google.protobuf.Timestamp
}
var file_install_event_proto_depIdxs = []int32{
	5, // 0: protobuf.CreateInstallEventRequest.event_time:type_name -> google.protobuf.Timestamp
	4, // 1: protobuf.CreateInstallEventRequest.signature_params:type_name -> protobuf.CreateInstallEventRequest.SignatureParamsEntry
	0, // 2: protobuf.CreateInstallEventBatchRequest.events:type_name -> protobuf.CreateInstallEventRequest
	0, // 3: protobuf.InstallEventService.CreateInstallEvent:input_type -> protobuf.CreateInstallEventRequest
	2, // 4: protobuf.InstallEventService.CreateInstallEventBatch:input_type -> protobuf.CreateInstallEventBatchRequest
	1, // 5: protobuf.InstallEventService.CreateInstallEvent:output_type -> protobuf.CreateInstallEventResponse
	3, // 6: protobuf.InstallEventService.CreateInstallEventBatch:output_type -> protobuf.CreateInstallEventBatchResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_install_event_proto_init() }
func file_install_event_proto_init() {
	if File_install_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_install_event_proto_rawDesc), len(file_install_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_install_event_proto_goTypes,
		DependencyIndexes: file_install_event_proto_depIdxs,
		MessageInfos:      file_install_event_proto_msgTypes,
	}.Build()
	File_install_event_proto = out.File
	file_install_event_proto_goTypes = nil
	file_install_event_proto_depIdxs = nil
}
